import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  apiSidebar: [
    { type: 'autogenerated', dirName: '@sgrnext-api' },
  ],
  pluginsSidebar: [
    { type: 'autogenerated', dirName: 'plugins' },
  ],
};

export default sidebars;
